### ISSUE TITLE
Scala 2.11 : java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/docker-ubuntu-adam#3]
## Problem

```
root@cdeabaeb05b0:/usr/local/adam-scala-2.11/bin# ./adam-submit  vcf2adam -onlyvariants /data/All_20150603.vcf /data/All_20150603.adam2
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/spark/bin/spark-submit
Spark assembly has been built with Hive, including Datanucleus jars on classpath
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
    at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:120)
    at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:77)
    at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
## Related Issues

https://groups.google.com/forum/#!topic/adam-developers/j5bzgpK5-aU

Seems to be an issue upstream (Adam, Spark ?) with Scala 2.11

**Comment by Pavan637** [comment]
I am using scala 2.10.4 for spark 1.5.2 and still getting the same error as "Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;"
while running adam-submit transform adam/adam-core/src/test/resources/small.sam small.adam comamnd.
Any help will be greatly appreciated

**Comment by davidonlaptop** [comment]
Hi @Pavan637 , you may have better luck to report the bug in adam repo.

**Comment by srinivas-thammanaboina** [comment]
Use scala 2.11.8. see the spark download documentation for version compatibility.
